services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: demo
      MYSQL_PASSWORD: thePassword
      MYSQL_DATABASE: customer_DB
    ports:
      - '3306'
